_id: 67936f3650613db0cdc5eee5
id: Ashcomposer/jina-embeddings-v2-base-zh-Q8_0-GGUF
private: false
pipeline_tag: feature-extraction
library_name: sentence-transformers
tags:
- sentence-transformers
- gguf
- feature-extraction
- sentence-similarity
- mteb
- transformers
- transformers.js
- llama-cpp
- gguf-my-repo
- en
- zh
- base_model:jinaai/jina-embeddings-v2-base-zh
- base_model:quantized:jinaai/jina-embeddings-v2-base-zh
- license:apache-2.0
- model-index
- region:us
downloads: 10
likes: 1
modelId: Ashcomposer/jina-embeddings-v2-base-zh-Q8_0-GGUF
author: Ashcomposer
sha: 08640c617c122a895922774c1238f42873359cc1
lastModified: '2025-01-24T10:45:12.000Z'
gated: false
disabled: false
model-index:
- name: jina-embeddings-v2-base-zh
  results:
  - task:
      type: STS
    dataset:
      name: MTEB AFQMC
      type: C-MTEB/AFQMC
      config: default
      split: validation
      revision: None
    metrics:
    - type: cos_sim_pearson
      value: 48.51403119231363
      verified: false
    - type: cos_sim_spearman
      value: 50.5928547846445
      verified: false
    - type: euclidean_pearson
      value: 48.750436310559074
      verified: false
    - type: euclidean_spearman
      value: 50.50950238691385
      verified: false
    - type: manhattan_pearson
      value: 48.7866189440328
      verified: false
    - type: manhattan_spearman
      value: 50.58692402017165
      verified: false
  - task:
      type: STS
    dataset:
      name: MTEB ATEC
      type: C-MTEB/ATEC
      config: default
      split: test
      revision: None
    metrics:
    - type: cos_sim_pearson
      value: 50.25985700105725
      verified: false
    - type: cos_sim_spearman
      value: 51.28815934593989
      verified: false
    - type: euclidean_pearson
      value: 52.70329248799904
      verified: false
    - type: euclidean_spearman
      value: 50.94101139559258
      verified: false
    - type: manhattan_pearson
      value: 52.6647237400892
      verified: false
    - type: manhattan_spearman
      value: 50.922441325406176
      verified: false
  - task:
      type: Classification
    dataset:
      name: MTEB AmazonReviewsClassification (zh)
      type: mteb/amazon_reviews_multi
      config: zh
      split: test
      revision: 1399c76144fd37290681b995c656ef9b2e06e26d
    metrics:
    - type: accuracy
      value: 34.944
      verified: false
    - type: f1
      value: 34.06478860660109
      verified: false
  - task:
      type: STS
    dataset:
      name: MTEB BQ
      type: C-MTEB/BQ
      config: default
      split: test
      revision: None
    metrics:
    - type: cos_sim_pearson
      value: 65.15667035488342
      verified: false
    - type: cos_sim_spearman
      value: 66.07110142081
      verified: false
    - type: euclidean_pearson
      value: 60.447598102249714
      verified: false
    - type: euclidean_spearman
      value: 61.826575796578766
      verified: false
    - type: manhattan_pearson
      value: 60.39364279354984
      verified: false
    - type: manhattan_spearman
      value: 61.78743491223281
      verified: false
  - task:
      type: Clustering
    dataset:
      name: MTEB CLSClusteringP2P
      type: C-MTEB/CLSClusteringP2P
      config: default
      split: test
      revision: None
    metrics:
    - type: v_measure
      value: 39.96714175391701
      verified: false
  - task:
      type: Clustering
    dataset:
      name: MTEB CLSClusteringS2S
      type: C-MTEB/CLSClusteringS2S
      config: default
      split: test
      revision: None
    metrics:
    - type: v_measure
      value: 38.39863566717934
      verified: false
  - task:
      type: Reranking
    dataset:
      name: MTEB CMedQAv1
      type: C-MTEB/CMedQAv1-reranking
      config: default
      split: test
      revision: None
    metrics:
    - type: map
      value: 83.63680381780644
      verified: false
    - type: mrr
      value: 86.16476190476192
      verified: false
  - task:
      type: Reranking
    dataset:
      name: MTEB CMedQAv2
      type: C-MTEB/CMedQAv2-reranking
      config: default
      split: test
      revision: None
    metrics:
    - type: map
      value: 83.74350667859487
      verified: false
    - type: mrr
      value: 86.10388888888889
      verified: false
  - task:
      type: Retrieval
    dataset:
      name: MTEB CmedqaRetrieval
      type: C-MTEB/CmedqaRetrieval
      config: default
      split: dev
      revision: None
    metrics:
    - type: map_at_1
      value: 22.072
      verified: false
    - type: map_at_10
      value: 32.942
      verified: false
    - type: map_at_100
      value: 34.768
      verified: false
    - type: map_at_1000
      value: 34.902
      verified: false
    - type: map_at_3
      value: 29.357
      verified: false
    - type: map_at_5
      value: 31.236000000000004
      verified: false
    - type: mrr_at_1
      value: 34.259
      verified: false
    - type: mrr_at_10
      value: 41.957
      verified: false
    - type: mrr_at_100
      value: 42.982
      verified: false
    - type: mrr_at_1000
      value: 43.042
      verified: false
    - type: mrr_at_3
      value: 39.722
      verified: false
    - type: mrr_at_5
      value: 40.898
      verified: false
    - type: ndcg_at_1
      value: 34.259
      verified: false
    - type: ndcg_at_10
      value: 39.153
      verified: false
    - type: ndcg_at_100
      value: 46.493
      verified: false
    - type: ndcg_at_1000
      value: 49.01
      verified: false
    - type: ndcg_at_3
      value: 34.636
      verified: false
    - type: ndcg_at_5
      value: 36.278
      verified: false
    - type: precision_at_1
      value: 34.259
      verified: false
    - type: precision_at_10
      value: 8.815000000000001
      verified: false
    - type: precision_at_100
      value: 1.474
      verified: false
    - type: precision_at_1000
      value: 0.179
      verified: false
    - type: precision_at_3
      value: 19.73
      verified: false
    - type: precision_at_5
      value: 14.174000000000001
      verified: false
    - type: recall_at_1
      value: 22.072
      verified: false
    - type: recall_at_10
      value: 48.484
      verified: false
    - type: recall_at_100
      value: 79.035
      verified: false
    - type: recall_at_1000
      value: 96.15
      verified: false
    - type: recall_at_3
      value: 34.607
      verified: false
    - type: recall_at_5
      value: 40.064
      verified: false
  - task:
      type: PairClassification
    dataset:
      name: MTEB Cmnli
      type: C-MTEB/CMNLI
      config: default
      split: validation
      revision: None
    metrics:
    - type: cos_sim_accuracy
      value: 76.7047504509922
      verified: false
    - type: cos_sim_ap
      value: 85.26649874800871
      verified: false
    - type: cos_sim_f1
      value: 78.13528724646915
      verified: false
    - type: cos_sim_precision
      value: 71.57587548638132
      verified: false
    - type: cos_sim_recall
      value: 86.01823708206688
      verified: false
    - type: dot_accuracy
      value: 70.13830426939266
      verified: false
    - type: dot_ap
      value: 77.01510412382171
      verified: false
    - type: dot_f1
      value: 73.56710042713817
      verified: false
    - type: dot_precision
      value: 63.955094991364426
      verified: false
    - type: dot_recall
      value: 86.57937806873977
      verified: false
    - type: euclidean_accuracy
      value: 75.53818400481059
      verified: false
    - type: euclidean_ap
      value: 84.34668448241264
      verified: false
    - type: euclidean_f1
      value: 77.51741608613047
      verified: false
    - type: euclidean_precision
      value: 70.65614777756399
      verified: false
    - type: euclidean_recall
      value: 85.85457096095394
      verified: false
    - type: manhattan_accuracy
      value: 75.49007817197835
      verified: false
    - type: manhattan_ap
      value: 84.40297506704299
      verified: false
    - type: manhattan_f1
      value: 77.63185324160932
      verified: false
    - type: manhattan_precision
      value: 70.03949595636637
      verified: false
    - type: manhattan_recall
      value: 87.07037643207856
      verified: false
    - type: max_accuracy
      value: 76.7047504509922
      verified: false
    - type: max_ap
      value: 85.26649874800871
      verified: false
    - type: max_f1
      value: 78.13528724646915
      verified: false
  - task:
      type: Retrieval
    dataset:
      name: MTEB CovidRetrieval
      type: C-MTEB/CovidRetrieval
      config: default
      split: dev
      revision: None
    metrics:
    - type: map_at_1
      value: 69.178
      verified: false
    - type: map_at_10
      value: 77.523
      verified: false
    - type: map_at_100
      value: 77.793
      verified: false
    - type: map_at_1000
      value: 77.79899999999999
      verified: false
    - type: map_at_3
      value: 75.878
      verified: false
    - type: map_at_5
      value: 76.849
      verified: false
    - type: mrr_at_1
      value: 69.44200000000001
      verified: false
    - type: mrr_at_10
      value: 77.55
      verified: false
    - type: mrr_at_100
      value: 77.819
      verified: false
    - type: mrr_at_1000
      value: 77.826
      verified: false
    - type: mrr_at_3
      value: 75.957
      verified: false
    - type: mrr_at_5
      value: 76.916
      verified: false
    - type: ndcg_at_1
      value: 69.44200000000001
      verified: false
    - type: ndcg_at_10
      value: 81.217
      verified: false
    - type: ndcg_at_100
      value: 82.45
      verified: false
    - type: ndcg_at_1000
      value: 82.636
      verified: false
    - type: ndcg_at_3
      value: 77.931
      verified: false
    - type: ndcg_at_5
      value: 79.655
      verified: false
    - type: precision_at_1
      value: 69.44200000000001
      verified: false
    - type: precision_at_10
      value: 9.357
      verified: false
    - type: precision_at_100
      value: 0.993
      verified: false
    - type: precision_at_1000
      value: 0.101
      verified: false
    - type: precision_at_3
      value: 28.1
      verified: false
    - type: precision_at_5
      value: 17.724
      verified: false
    - type: recall_at_1
      value: 69.178
      verified: false
    - type: recall_at_10
      value: 92.624
      verified: false
    - type: recall_at_100
      value: 98.209
      verified: false
    - type: recall_at_1000
      value: 99.684
      verified: false
    - type: recall_at_3
      value: 83.772
      verified: false
    - type: recall_at_5
      value: 87.882
      verified: false
  - task:
      type: Retrieval
    dataset:
      name: MTEB DuRetrieval
      type: C-MTEB/DuRetrieval
      config: default
      split: dev
      revision: None
    metrics:
    - type: map_at_1
      value: 25.163999999999998
      verified: false
    - type: map_at_10
      value: 76.386
      verified: false
    - type: map_at_100
      value: 79.339
      verified: false
    - type: map_at_1000
      value: 79.39500000000001
      verified: false
    - type: map_at_3
      value: 52.959
      verified: false
    - type: map_at_5
      value: 66.59
      verified: false
    - type: mrr_at_1
      value: 87.9
      verified: false
    - type: mrr_at_10
      value: 91.682
      verified: false
    - type: mrr_at_100
      value: 91.747
      verified: false
    - type: mrr_at_1000
      value: 91.751
      verified: false
    - type: mrr_at_3
      value: 91.267
      verified: false
    - type: mrr_at_5
      value: 91.527
      verified: false
    - type: ndcg_at_1
      value: 87.9
      verified: false
    - type: ndcg_at_10
      value: 84.569
      verified: false
    - type: ndcg_at_100
      value: 87.83800000000001
      verified: false
    - type: ndcg_at_1000
      value: 88.322
      verified: false
    - type: ndcg_at_3
      value: 83.473
      verified: false
    - type: ndcg_at_5
      value: 82.178
      verified: false
    - type: precision_at_1
      value: 87.9
      verified: false
    - type: precision_at_10
      value: 40.605000000000004
      verified: false
    - type: precision_at_100
      value: 4.752
      verified: false
    - type: precision_at_1000
      value: 0.488
      verified: false
    - type: precision_at_3
      value: 74.9
      verified: false
    - type: precision_at_5
      value: 62.96000000000001
      verified: false
    - type: recall_at_1
      value: 25.163999999999998
      verified: false
    - type: recall_at_10
      value: 85.97399999999999
      verified: false
    - type: recall_at_100
      value: 96.63000000000001
      verified: false
    - type: recall_at_1000
      value: 99.016
      verified: false
    - type: recall_at_3
      value: 55.611999999999995
      verified: false
    - type: recall_at_5
      value: 71.936
      verified: false
  - task:
      type: Retrieval
    dataset:
      name: MTEB EcomRetrieval
      type: C-MTEB/EcomRetrieval
      config: default
      split: dev
      revision: None
    metrics:
    - type: map_at_1
      value: 48.6
      verified: false
    - type: map_at_10
      value: 58.831
      verified: false
    - type: map_at_100
      value: 59.427
      verified: false
    - type: map_at_1000
      value: 59.44199999999999
      verified: false
    - type: map_at_3
      value: 56.383
      verified: false
    - type: map_at_5
      value: 57.753
      verified: false
    - type: mrr_at_1
      value: 48.6
      verified: false
    - type: mrr_at_10
      value: 58.831
      verified: false
    - type: mrr_at_100
      value: 59.427
      verified: false
    - type: mrr_at_1000
      value: 59.44199999999999
      verified: false
    - type: mrr_at_3
      value: 56.383
      verified: false
    - type: mrr_at_5
      value: 57.753
      verified: false
    - type: ndcg_at_1
      value: 48.6
      verified: false
    - type: ndcg_at_10
      value: 63.951
      verified: false
    - type: ndcg_at_100
      value: 66.72200000000001
      verified: false
    - type: ndcg_at_1000
      value: 67.13900000000001
      verified: false
    - type: ndcg_at_3
      value: 58.882
      verified: false
    - type: ndcg_at_5
      value: 61.373
      verified: false
    - type: precision_at_1
      value: 48.6
      verified: false
    - type: precision_at_10
      value: 8.01
      verified: false
    - type: precision_at_100
      value: 0.928
      verified: false
    - type: precision_at_1000
      value: 0.096
      verified: false
    - type: precision_at_3
      value: 22.033
      verified: false
    - type: precision_at_5
      value: 14.44
      verified: false
    - type: recall_at_1
      value: 48.6
      verified: false
    - type: recall_at_10
      value: 80.10000000000001
      verified: false
    - type: recall_at_100
      value: 92.80000000000001
      verified: false
    - type: recall_at_1000
      value: 96.1
      verified: false
    - type: recall_at_3
      value: 66.10000000000001
      verified: false
    - type: recall_at_5
      value: 72.2
      verified: false
  - task:
      type: Classification
    dataset:
      name: MTEB IFlyTek
      type: C-MTEB/IFlyTek-classification
      config: default
      split: validation
      revision: None
    metrics:
    - type: accuracy
      value: 47.36437091188918
      verified: false
    - type: f1
      value: 36.60946954228577
      verified: false
  - task:
      type: Classification
    dataset:
      name: MTEB JDReview
      type: C-MTEB/JDReview-classification
      config: default
      split: test
      revision: None
    metrics:
    - type: accuracy
      value: 79.5684803001876
      verified: false
    - type: ap
      value: 42.671935929201524
      verified: false
    - type: f1
      value: 73.31912729103752
      verified: false
  - task:
      type: STS
    dataset:
      name: MTEB LCQMC
      type: C-MTEB/LCQMC
      config: default
      split: test
      revision: None
    metrics:
    - type: cos_sim_pearson
      value: 68.62670112113864
      verified: false
    - type: cos_sim_spearman
      value: 75.74009123170768
      verified: false
    - type: euclidean_pearson
      value: 73.93002595958237
      verified: false
    - type: euclidean_spearman
      value: 75.35222935003587
      verified: false
    - type: manhattan_pearson
      value: 73.89870445158144
      verified: false
    - type: manhattan_spearman
      value: 75.31714936339398
      verified: false
  - task:
      type: Reranking
    dataset:
      name: MTEB MMarcoReranking
      type: C-MTEB/Mmarco-reranking
      config: default
      split: dev
      revision: None
    metrics:
    - type: map
      value: 31.5372713650176
      verified: false
    - type: mrr
      value: 30.163095238095238
      verified: false
  - task:
      type: Retrieval
    dataset:
      name: MTEB MMarcoRetrieval
      type: C-MTEB/MMarcoRetrieval
      config: default
      split: dev
      revision: None
    metrics:
    - type: map_at_1
      value: 65.054
      verified: false
    - type: map_at_10
      value: 74.156
      verified: false
    - type: map_at_100
      value: 74.523
      verified: false
    - type: map_at_1000
      value: 74.535
      verified: false
    - type: map_at_3
      value: 72.269
      verified: false
    - type: map_at_5
      value: 73.41
      verified: false
    - type: mrr_at_1
      value: 67.24900000000001
      verified: false
    - type: mrr_at_10
      value: 74.78399999999999
      verified: false
    - type: mrr_at_100
      value: 75.107
      verified: false
    - type: mrr_at_1000
      value: 75.117
      verified: false
    - type: mrr_at_3
      value: 73.13499999999999
      verified: false
    - type: mrr_at_5
      value: 74.13499999999999
      verified: false
    - type: ndcg_at_1
      value: 67.24900000000001
      verified: false
    - type: ndcg_at_10
      value: 77.96300000000001
      verified: false
    - type: ndcg_at_100
      value: 79.584
      verified: false
    - type: ndcg_at_1000
      value: 79.884
      verified: false
    - type: ndcg_at_3
      value: 74.342
      verified: false
    - type: ndcg_at_5
      value: 76.278
      verified: false
    - type: precision_at_1
      value: 67.24900000000001
      verified: false
    - type: precision_at_10
      value: 9.466
      verified: false
    - type: precision_at_100
      value: 1.027
      verified: false
    - type: precision_at_1000
      value: 0.105
      verified: false
    - type: precision_at_3
      value: 27.955999999999996
      verified: false
    - type: precision_at_5
      value: 17.817
      verified: false
    - type: recall_at_1
      value: 65.054
      verified: false
    - type: recall_at_10
      value: 89.113
      verified: false
    - type: recall_at_100
      value: 96.369
      verified: false
    - type: recall_at_1000
      value: 98.714
      verified: false
    - type: recall_at_3
      value: 79.45400000000001
      verified: false
    - type: recall_at_5
      value: 84.06
      verified: false
  - task:
      type: Classification
    dataset:
      name: MTEB MassiveIntentClassification (zh-CN)
      type: mteb/amazon_massive_intent
      config: zh-CN
      split: test
      revision: 31efe3c427b0bae9c22cbb560b8f15491cc6bed7
    metrics:
    - type: accuracy
      value: 68.1977135171486
      verified: false
    - type: f1
      value: 67.23114308718404
      verified: false
  - task:
      type: Classification
    dataset:
      name: MTEB MassiveScenarioClassification (zh-CN)
      type: mteb/amazon_massive_scenario
      config: zh-CN
      split: test
      revision: 7d571f92784cd94a019292a1f45445077d0ef634
    metrics:
    - type: accuracy
      value: 71.92669804976462
      verified: false
    - type: f1
      value: 72.90628475628779
      verified: false
  - task:
      type: Retrieval
    dataset:
      name: MTEB MedicalRetrieval
      type: C-MTEB/MedicalRetrieval
      config: default
      split: dev
      revision: None
    metrics:
    - type: map_at_1
      value: 49.2
      verified: false
    - type: map_at_10
      value: 54.539
      verified: false
    - type: map_at_100
      value: 55.135
      verified: false
    - type: map_at_1000
      value: 55.19199999999999
      verified: false
    - type: map_at_3
      value: 53.383
      verified: false
    - type: map_at_5
      value: 54.142999999999994
      verified: false
    - type: mrr_at_1
      value: 49.2
      verified: false
    - type: mrr_at_10
      value: 54.539
      verified: false
    - type: mrr_at_100
      value: 55.135999999999996
      verified: false
    - type: mrr_at_1000
      value: 55.19199999999999
      verified: false
    - type: mrr_at_3
      value: 53.383
      verified: false
    - type: mrr_at_5
      value: 54.142999999999994
      verified: false
    - type: ndcg_at_1
      value: 49.2
      verified: false
    - type: ndcg_at_10
      value: 57.123000000000005
      verified: false
    - type: ndcg_at_100
      value: 60.21300000000001
      verified: false
    - type: ndcg_at_1000
      value: 61.915
      verified: false
    - type: ndcg_at_3
      value: 54.772
      verified: false
    - type: ndcg_at_5
      value: 56.157999999999994
      verified: false
    - type: precision_at_1
      value: 49.2
      verified: false
    - type: precision_at_10
      value: 6.52
      verified: false
    - type: precision_at_100
      value: 0.8009999999999999
      verified: false
    - type: precision_at_1000
      value: 0.094
      verified: false
    - type: precision_at_3
      value: 19.6
      verified: false
    - type: precision_at_5
      value: 12.44
      verified: false
    - type: recall_at_1
      value: 49.2
      verified: false
    - type: recall_at_10
      value: 65.2
      verified: false
    - type: recall_at_100
      value: 80.10000000000001
      verified: false
    - type: recall_at_1000
      value: 93.89999999999999
      verified: false
    - type: recall_at_3
      value: 58.8
      verified: false
    - type: recall_at_5
      value: 62.2
      verified: false
  - task:
      type: Classification
    dataset:
      name: MTEB MultilingualSentiment
      type: C-MTEB/MultilingualSentiment-classification
      config: default
      split: validation
      revision: None
    metrics:
    - type: accuracy
      value: 63.29333333333334
      verified: false
    - type: f1
      value: 63.03293854259612
      verified: false
  - task:
      type: PairClassification
    dataset:
      name: MTEB Ocnli
      type: C-MTEB/OCNLI
      config: default
      split: validation
      revision: None
    metrics:
    - type: cos_sim_accuracy
      value: 75.69030860855442
      verified: false
    - type: cos_sim_ap
      value: 80.6157833772759
      verified: false
    - type: cos_sim_f1
      value: 77.87524366471735
      verified: false
    - type: cos_sim_precision
      value: 72.3076923076923
      verified: false
    - type: cos_sim_recall
      value: 84.37170010559663
      verified: false
    - type: dot_accuracy
      value: 67.78559826746074
      verified: false
    - type: dot_ap
      value: 72.00871467527499
      verified: false
    - type: dot_f1
      value: 72.58722247394654
      verified: false
    - type: dot_precision
      value: 63.57142857142857
      verified: false
    - type: dot_recall
      value: 84.58289334741288
      verified: false
    - type: euclidean_accuracy
      value: 75.20303194369248
      verified: false
    - type: euclidean_ap
      value: 80.98587256415605
      verified: false
    - type: euclidean_f1
      value: 77.26396917148362
      verified: false
    - type: euclidean_precision
      value: 71.03631532329496
      verified: false
    - type: euclidean_recall
      value: 84.68848996832101
      verified: false
    - type: manhattan_accuracy
      value: 75.20303194369248
      verified: false
    - type: manhattan_ap
      value: 80.93460699513219
      verified: false
    - type: manhattan_f1
      value: 77.124773960217
      verified: false
    - type: manhattan_precision
      value: 67.43083003952569
      verified: false
    - type: manhattan_recall
      value: 90.07391763463569
      verified: false
    - type: max_accuracy
      value: 75.69030860855442
      verified: false
    - type: max_ap
      value: 80.98587256415605
      verified: false
    - type: max_f1
      value: 77.87524366471735
      verified: false
  - task:
      type: Classification
    dataset:
      name: MTEB OnlineShopping
      type: C-MTEB/OnlineShopping-classification
      config: default
      split: test
      revision: None
    metrics:
    - type: accuracy
      value: 87.00000000000001
      verified: false
    - type: ap
      value: 83.24372135949511
      verified: false
    - type: f1
      value: 86.95554191530607
      verified: false
  - task:
      type: STS
    dataset:
      name: MTEB PAWSX
      type: C-MTEB/PAWSX
      config: default
      split: test
      revision: None
    metrics:
    - type: cos_sim_pearson
      value: 37.57616811591219
      verified: false
    - type: cos_sim_spearman
      value: 41.490259084930045
      verified: false
    - type: euclidean_pearson
      value: 38.9155043692188
      verified: false
    - type: euclidean_spearman
      value: 39.16056534305623
      verified: false
    - type: manhattan_pearson
      value: 38.76569892264335
      verified: false
    - type: manhattan_spearman
      value: 38.99891685590743
      verified: false
  - task:
      type: STS
    dataset:
      name: MTEB QBQTC
      type: C-MTEB/QBQTC
      config: default
      split: test
      revision: None
    metrics:
    - type: cos_sim_pearson
      value: 35.44858610359665
      verified: false
    - type: cos_sim_spearman
      value: 38.11128146262466
      verified: false
    - type: euclidean_pearson
      value: 31.928644189822457
      verified: false
    - type: euclidean_spearman
      value: 34.384936631696554
      verified: false
    - type: manhattan_pearson
      value: 31.90586687414376
      verified: false
    - type: manhattan_spearman
      value: 34.35770153777186
      verified: false
  - task:
      type: STS
    dataset:
      name: MTEB STS22 (zh)
      type: mteb/sts22-crosslingual-sts
      config: zh
      split: test
      revision: 6d1ba47164174a496b7fa5d3569dae26a6813b80
    metrics:
    - type: cos_sim_pearson
      value: 66.54931957553592
      verified: false
    - type: cos_sim_spearman
      value: 69.25068863016632
      verified: false
    - type: euclidean_pearson
      value: 50.26525596106869
      verified: false
    - type: euclidean_spearman
      value: 63.83352741910006
      verified: false
    - type: manhattan_pearson
      value: 49.98798282198196
      verified: false
    - type: manhattan_spearman
      value: 63.87649521907841
      verified: false
  - task:
      type: STS
    dataset:
      name: MTEB STSB
      type: C-MTEB/STSB
      config: default
      split: test
      revision: None
    metrics:
    - type: cos_sim_pearson
      value: 82.52782476625825
      verified: false
    - type: cos_sim_spearman
      value: 82.55618986168398
      verified: false
    - type: euclidean_pearson
      value: 78.48190631687673
      verified: false
    - type: euclidean_spearman
      value: 78.39479731354655
      verified: false
    - type: manhattan_pearson
      value: 78.51176592165885
      verified: false
    - type: manhattan_spearman
      value: 78.42363787303265
      verified: false
  - task:
      type: Reranking
    dataset:
      name: MTEB T2Reranking
      type: C-MTEB/T2Reranking
      config: default
      split: dev
      revision: None
    metrics:
    - type: map
      value: 67.36693873615643
      verified: false
    - type: mrr
      value: 77.83847701797939
      verified: false
  - task:
      type: Retrieval
    dataset:
      name: MTEB T2Retrieval
      type: C-MTEB/T2Retrieval
      config: default
      split: dev
      revision: None
    metrics:
    - type: map_at_1
      value: 25.795
      verified: false
    - type: map_at_10
      value: 72.258
      verified: false
    - type: map_at_100
      value: 76.049
      verified: false
    - type: map_at_1000
      value: 76.134
      verified: false
    - type: map_at_3
      value: 50.697
      verified: false
    - type: map_at_5
      value: 62.324999999999996
      verified: false
    - type: mrr_at_1
      value: 86.634
      verified: false
    - type: mrr_at_10
      value: 89.792
      verified: false
    - type: mrr_at_100
      value: 89.91900000000001
      verified: false
    - type: mrr_at_1000
      value: 89.923
      verified: false
    - type: mrr_at_3
      value: 89.224
      verified: false
    - type: mrr_at_5
      value: 89.608
      verified: false
    - type: ndcg_at_1
      value: 86.634
      verified: false
    - type: ndcg_at_10
      value: 80.589
      verified: false
    - type: ndcg_at_100
      value: 84.812
      verified: false
    - type: ndcg_at_1000
      value: 85.662
      verified: false
    - type: ndcg_at_3
      value: 82.169
      verified: false
    - type: ndcg_at_5
      value: 80.619
      verified: false
    - type: precision_at_1
      value: 86.634
      verified: false
    - type: precision_at_10
      value: 40.389
      verified: false
    - type: precision_at_100
      value: 4.93
      verified: false
    - type: precision_at_1000
      value: 0.513
      verified: false
    - type: precision_at_3
      value: 72.104
      verified: false
    - type: precision_at_5
      value: 60.425
      verified: false
    - type: recall_at_1
      value: 25.795
      verified: false
    - type: recall_at_10
      value: 79.565
      verified: false
    - type: recall_at_100
      value: 93.24799999999999
      verified: false
    - type: recall_at_1000
      value: 97.595
      verified: false
    - type: recall_at_3
      value: 52.583999999999996
      verified: false
    - type: recall_at_5
      value: 66.175
      verified: false
  - task:
      type: Classification
    dataset:
      name: MTEB TNews
      type: C-MTEB/TNews-classification
      config: default
      split: validation
      revision: None
    metrics:
    - type: accuracy
      value: 47.648999999999994
      verified: false
    - type: f1
      value: 46.28925837008413
      verified: false
  - task:
      type: Clustering
    dataset:
      name: MTEB ThuNewsClusteringP2P
      type: C-MTEB/ThuNewsClusteringP2P
      config: default
      split: test
      revision: None
    metrics:
    - type: v_measure
      value: 54.07641891287953
      verified: false
  - task:
      type: Clustering
    dataset:
      name: MTEB ThuNewsClusteringS2S
      type: C-MTEB/ThuNewsClusteringS2S
      config: default
      split: test
      revision: None
    metrics:
    - type: v_measure
      value: 53.423702062353954
      verified: false
  - task:
      type: Retrieval
    dataset:
      name: MTEB VideoRetrieval
      type: C-MTEB/VideoRetrieval
      config: default
      split: dev
      revision: None
    metrics:
    - type: map_at_1
      value: 55.7
      verified: false
    - type: map_at_10
      value: 65.923
      verified: false
    - type: map_at_100
      value: 66.42
      verified: false
    - type: map_at_1000
      value: 66.431
      verified: false
    - type: map_at_3
      value: 63.9
      verified: false
    - type: map_at_5
      value: 65.225
      verified: false
    - type: mrr_at_1
      value: 55.60000000000001
      verified: false
    - type: mrr_at_10
      value: 65.873
      verified: false
    - type: mrr_at_100
      value: 66.36999999999999
      verified: false
    - type: mrr_at_1000
      value: 66.381
      verified: false
    - type: mrr_at_3
      value: 63.849999999999994
      verified: false
    - type: mrr_at_5
      value: 65.17500000000001
      verified: false
    - type: ndcg_at_1
      value: 55.7
      verified: false
    - type: ndcg_at_10
      value: 70.621
      verified: false
    - type: ndcg_at_100
      value: 72.944
      verified: false
    - type: ndcg_at_1000
      value: 73.25399999999999
      verified: false
    - type: ndcg_at_3
      value: 66.547
      verified: false
    - type: ndcg_at_5
      value: 68.93599999999999
      verified: false
    - type: precision_at_1
      value: 55.7
      verified: false
    - type: precision_at_10
      value: 8.52
      verified: false
    - type: precision_at_100
      value: 0.958
      verified: false
    - type: precision_at_1000
      value: 0.098
      verified: false
    - type: precision_at_3
      value: 24.733
      verified: false
    - type: precision_at_5
      value: 16
      verified: false
    - type: recall_at_1
      value: 55.7
      verified: false
    - type: recall_at_10
      value: 85.2
      verified: false
    - type: recall_at_100
      value: 95.8
      verified: false
    - type: recall_at_1000
      value: 98.3
      verified: false
    - type: recall_at_3
      value: 74.2
      verified: false
    - type: recall_at_5
      value: 80
      verified: false
  - task:
      type: Classification
    dataset:
      name: MTEB Waimai
      type: C-MTEB/waimai-classification
      config: default
      split: test
      revision: None
    metrics:
    - type: accuracy
      value: 84.54
      verified: false
    - type: ap
      value: 66.13603199670062
      verified: false
    - type: f1
      value: 82.61420654584116
      verified: false
config: {}
cardData:
  tags:
  - sentence-transformers
  - feature-extraction
  - sentence-similarity
  - mteb
  - transformers
  - transformers.js
  - llama-cpp
  - gguf-my-repo
  inference: false
  license: apache-2.0
  language:
  - en
  - zh
  base_model: jinaai/jina-embeddings-v2-base-zh
  model-index:
  - name: jina-embeddings-v2-base-zh
    results:
    - task:
        type: STS
      dataset:
        name: MTEB AFQMC
        type: C-MTEB/AFQMC
        config: default
        split: validation
        revision: None
      metrics:
      - type: cos_sim_pearson
        value: 48.51403119231363
        verified: false
      - type: cos_sim_spearman
        value: 50.5928547846445
        verified: false
      - type: euclidean_pearson
        value: 48.750436310559074
        verified: false
      - type: euclidean_spearman
        value: 50.50950238691385
        verified: false
      - type: manhattan_pearson
        value: 48.7866189440328
        verified: false
      - type: manhattan_spearman
        value: 50.58692402017165
        verified: false
    - task:
        type: STS
      dataset:
        name: MTEB ATEC
        type: C-MTEB/ATEC
        config: default
        split: test
        revision: None
      metrics:
      - type: cos_sim_pearson
        value: 50.25985700105725
        verified: false
      - type: cos_sim_spearman
        value: 51.28815934593989
        verified: false
      - type: euclidean_pearson
        value: 52.70329248799904
        verified: false
      - type: euclidean_spearman
        value: 50.94101139559258
        verified: false
      - type: manhattan_pearson
        value: 52.6647237400892
        verified: false
      - type: manhattan_spearman
        value: 50.922441325406176
        verified: false
    - task:
        type: Classification
      dataset:
        name: MTEB AmazonReviewsClassification (zh)
        type: mteb/amazon_reviews_multi
        config: zh
        split: test
        revision: 1399c76144fd37290681b995c656ef9b2e06e26d
      metrics:
      - type: accuracy
        value: 34.944
        verified: false
      - type: f1
        value: 34.06478860660109
        verified: false
    - task:
        type: STS
      dataset:
        name: MTEB BQ
        type: C-MTEB/BQ
        config: default
        split: test
        revision: None
      metrics:
      - type: cos_sim_pearson
        value: 65.15667035488342
        verified: false
      - type: cos_sim_spearman
        value: 66.07110142081
        verified: false
      - type: euclidean_pearson
        value: 60.447598102249714
        verified: false
      - type: euclidean_spearman
        value: 61.826575796578766
        verified: false
      - type: manhattan_pearson
        value: 60.39364279354984
        verified: false
      - type: manhattan_spearman
        value: 61.78743491223281
        verified: false
    - task:
        type: Clustering
      dataset:
        name: MTEB CLSClusteringP2P
        type: C-MTEB/CLSClusteringP2P
        config: default
        split: test
        revision: None
      metrics:
      - type: v_measure
        value: 39.96714175391701
        verified: false
    - task:
        type: Clustering
      dataset:
        name: MTEB CLSClusteringS2S
        type: C-MTEB/CLSClusteringS2S
        config: default
        split: test
        revision: None
      metrics:
      - type: v_measure
        value: 38.39863566717934
        verified: false
    - task:
        type: Reranking
      dataset:
        name: MTEB CMedQAv1
        type: C-MTEB/CMedQAv1-reranking
        config: default
        split: test
        revision: None
      metrics:
      - type: map
        value: 83.63680381780644
        verified: false
      - type: mrr
        value: 86.16476190476192
        verified: false
    - task:
        type: Reranking
      dataset:
        name: MTEB CMedQAv2
        type: C-MTEB/CMedQAv2-reranking
        config: default
        split: test
        revision: None
      metrics:
      - type: map
        value: 83.74350667859487
        verified: false
      - type: mrr
        value: 86.10388888888889
        verified: false
    - task:
        type: Retrieval
      dataset:
        name: MTEB CmedqaRetrieval
        type: C-MTEB/CmedqaRetrieval
        config: default
        split: dev
        revision: None
      metrics:
      - type: map_at_1
        value: 22.072
        verified: false
      - type: map_at_10
        value: 32.942
        verified: false
      - type: map_at_100
        value: 34.768
        verified: false
      - type: map_at_1000
        value: 34.902
        verified: false
      - type: map_at_3
        value: 29.357
        verified: false
      - type: map_at_5
        value: 31.236000000000004
        verified: false
      - type: mrr_at_1
        value: 34.259
        verified: false
      - type: mrr_at_10
        value: 41.957
        verified: false
      - type: mrr_at_100
        value: 42.982
        verified: false
      - type: mrr_at_1000
        value: 43.042
        verified: false
      - type: mrr_at_3
        value: 39.722
        verified: false
      - type: mrr_at_5
        value: 40.898
        verified: false
      - type: ndcg_at_1
        value: 34.259
        verified: false
      - type: ndcg_at_10
        value: 39.153
        verified: false
      - type: ndcg_at_100
        value: 46.493
        verified: false
      - type: ndcg_at_1000
        value: 49.01
        verified: false
      - type: ndcg_at_3
        value: 34.636
        verified: false
      - type: ndcg_at_5
        value: 36.278
        verified: false
      - type: precision_at_1
        value: 34.259
        verified: false
      - type: precision_at_10
        value: 8.815000000000001
        verified: false
      - type: precision_at_100
        value: 1.474
        verified: false
      - type: precision_at_1000
        value: 0.179
        verified: false
      - type: precision_at_3
        value: 19.73
        verified: false
      - type: precision_at_5
        value: 14.174000000000001
        verified: false
      - type: recall_at_1
        value: 22.072
        verified: false
      - type: recall_at_10
        value: 48.484
        verified: false
      - type: recall_at_100
        value: 79.035
        verified: false
      - type: recall_at_1000
        value: 96.15
        verified: false
      - type: recall_at_3
        value: 34.607
        verified: false
      - type: recall_at_5
        value: 40.064
        verified: false
    - task:
        type: PairClassification
      dataset:
        name: MTEB Cmnli
        type: C-MTEB/CMNLI
        config: default
        split: validation
        revision: None
      metrics:
      - type: cos_sim_accuracy
        value: 76.7047504509922
        verified: false
      - type: cos_sim_ap
        value: 85.26649874800871
        verified: false
      - type: cos_sim_f1
        value: 78.13528724646915
        verified: false
      - type: cos_sim_precision
        value: 71.57587548638132
        verified: false
      - type: cos_sim_recall
        value: 86.01823708206688
        verified: false
      - type: dot_accuracy
        value: 70.13830426939266
        verified: false
      - type: dot_ap
        value: 77.01510412382171
        verified: false
      - type: dot_f1
        value: 73.56710042713817
        verified: false
      - type: dot_precision
        value: 63.955094991364426
        verified: false
      - type: dot_recall
        value: 86.57937806873977
        verified: false
      - type: euclidean_accuracy
        value: 75.53818400481059
        verified: false
      - type: euclidean_ap
        value: 84.34668448241264
        verified: false
      - type: euclidean_f1
        value: 77.51741608613047
        verified: false
      - type: euclidean_precision
        value: 70.65614777756399
        verified: false
      - type: euclidean_recall
        value: 85.85457096095394
        verified: false
      - type: manhattan_accuracy
        value: 75.49007817197835
        verified: false
      - type: manhattan_ap
        value: 84.40297506704299
        verified: false
      - type: manhattan_f1
        value: 77.63185324160932
        verified: false
      - type: manhattan_precision
        value: 70.03949595636637
        verified: false
      - type: manhattan_recall
        value: 87.07037643207856
        verified: false
      - type: max_accuracy
        value: 76.7047504509922
        verified: false
      - type: max_ap
        value: 85.26649874800871
        verified: false
      - type: max_f1
        value: 78.13528724646915
        verified: false
    - task:
        type: Retrieval
      dataset:
        name: MTEB CovidRetrieval
        type: C-MTEB/CovidRetrieval
        config: default
        split: dev
        revision: None
      metrics:
      - type: map_at_1
        value: 69.178
        verified: false
      - type: map_at_10
        value: 77.523
        verified: false
      - type: map_at_100
        value: 77.793
        verified: false
      - type: map_at_1000
        value: 77.79899999999999
        verified: false
      - type: map_at_3
        value: 75.878
        verified: false
      - type: map_at_5
        value: 76.849
        verified: false
      - type: mrr_at_1
        value: 69.44200000000001
        verified: false
      - type: mrr_at_10
        value: 77.55
        verified: false
      - type: mrr_at_100
        value: 77.819
        verified: false
      - type: mrr_at_1000
        value: 77.826
        verified: false
      - type: mrr_at_3
        value: 75.957
        verified: false
      - type: mrr_at_5
        value: 76.916
        verified: false
      - type: ndcg_at_1
        value: 69.44200000000001
        verified: false
      - type: ndcg_at_10
        value: 81.217
        verified: false
      - type: ndcg_at_100
        value: 82.45
        verified: false
      - type: ndcg_at_1000
        value: 82.636
        verified: false
      - type: ndcg_at_3
        value: 77.931
        verified: false
      - type: ndcg_at_5
        value: 79.655
        verified: false
      - type: precision_at_1
        value: 69.44200000000001
        verified: false
      - type: precision_at_10
        value: 9.357
        verified: false
      - type: precision_at_100
        value: 0.993
        verified: false
      - type: precision_at_1000
        value: 0.101
        verified: false
      - type: precision_at_3
        value: 28.1
        verified: false
      - type: precision_at_5
        value: 17.724
        verified: false
      - type: recall_at_1
        value: 69.178
        verified: false
      - type: recall_at_10
        value: 92.624
        verified: false
      - type: recall_at_100
        value: 98.209
        verified: false
      - type: recall_at_1000
        value: 99.684
        verified: false
      - type: recall_at_3
        value: 83.772
        verified: false
      - type: recall_at_5
        value: 87.882
        verified: false
    - task:
        type: Retrieval
      dataset:
        name: MTEB DuRetrieval
        type: C-MTEB/DuRetrieval
        config: default
        split: dev
        revision: None
      metrics:
      - type: map_at_1
        value: 25.163999999999998
        verified: false
      - type: map_at_10
        value: 76.386
        verified: false
      - type: map_at_100
        value: 79.339
        verified: false
      - type: map_at_1000
        value: 79.39500000000001
        verified: false
      - type: map_at_3
        value: 52.959
        verified: false
      - type: map_at_5
        value: 66.59
        verified: false
      - type: mrr_at_1
        value: 87.9
        verified: false
      - type: mrr_at_10
        value: 91.682
        verified: false
      - type: mrr_at_100
        value: 91.747
        verified: false
      - type: mrr_at_1000
        value: 91.751
        verified: false
      - type: mrr_at_3
        value: 91.267
        verified: false
      - type: mrr_at_5
        value: 91.527
        verified: false
      - type: ndcg_at_1
        value: 87.9
        verified: false
      - type: ndcg_at_10
        value: 84.569
        verified: false
      - type: ndcg_at_100
        value: 87.83800000000001
        verified: false
      - type: ndcg_at_1000
        value: 88.322
        verified: false
      - type: ndcg_at_3
        value: 83.473
        verified: false
      - type: ndcg_at_5
        value: 82.178
        verified: false
      - type: precision_at_1
        value: 87.9
        verified: false
      - type: precision_at_10
        value: 40.605000000000004
        verified: false
      - type: precision_at_100
        value: 4.752
        verified: false
      - type: precision_at_1000
        value: 0.488
        verified: false
      - type: precision_at_3
        value: 74.9
        verified: false
      - type: precision_at_5
        value: 62.96000000000001
        verified: false
      - type: recall_at_1
        value: 25.163999999999998
        verified: false
      - type: recall_at_10
        value: 85.97399999999999
        verified: false
      - type: recall_at_100
        value: 96.63000000000001
        verified: false
      - type: recall_at_1000
        value: 99.016
        verified: false
      - type: recall_at_3
        value: 55.611999999999995
        verified: false
      - type: recall_at_5
        value: 71.936
        verified: false
    - task:
        type: Retrieval
      dataset:
        name: MTEB EcomRetrieval
        type: C-MTEB/EcomRetrieval
        config: default
        split: dev
        revision: None
      metrics:
      - type: map_at_1
        value: 48.6
        verified: false
      - type: map_at_10
        value: 58.831
        verified: false
      - type: map_at_100
        value: 59.427
        verified: false
      - type: map_at_1000
        value: 59.44199999999999
        verified: false
      - type: map_at_3
        value: 56.383
        verified: false
      - type: map_at_5
        value: 57.753
        verified: false
      - type: mrr_at_1
        value: 48.6
        verified: false
      - type: mrr_at_10
        value: 58.831
        verified: false
      - type: mrr_at_100
        value: 59.427
        verified: false
      - type: mrr_at_1000
        value: 59.44199999999999
        verified: false
      - type: mrr_at_3
        value: 56.383
        verified: false
      - type: mrr_at_5
        value: 57.753
        verified: false
      - type: ndcg_at_1
        value: 48.6
        verified: false
      - type: ndcg_at_10
        value: 63.951
        verified: false
      - type: ndcg_at_100
        value: 66.72200000000001
        verified: false
      - type: ndcg_at_1000
        value: 67.13900000000001
        verified: false
      - type: ndcg_at_3
        value: 58.882
        verified: false
      - type: ndcg_at_5
        value: 61.373
        verified: false
      - type: precision_at_1
        value: 48.6
        verified: false
      - type: precision_at_10
        value: 8.01
        verified: false
      - type: precision_at_100
        value: 0.928
        verified: false
      - type: precision_at_1000
        value: 0.096
        verified: false
      - type: precision_at_3
        value: 22.033
        verified: false
      - type: precision_at_5
        value: 14.44
        verified: false
      - type: recall_at_1
        value: 48.6
        verified: false
      - type: recall_at_10
        value: 80.10000000000001
        verified: false
      - type: recall_at_100
        value: 92.80000000000001
        verified: false
      - type: recall_at_1000
        value: 96.1
        verified: false
      - type: recall_at_3
        value: 66.10000000000001
        verified: false
      - type: recall_at_5
        value: 72.2
        verified: false
    - task:
        type: Classification
      dataset:
        name: MTEB IFlyTek
        type: C-MTEB/IFlyTek-classification
        config: default
        split: validation
        revision: None
      metrics:
      - type: accuracy
        value: 47.36437091188918
        verified: false
      - type: f1
        value: 36.60946954228577
        verified: false
    - task:
        type: Classification
      dataset:
        name: MTEB JDReview
        type: C-MTEB/JDReview-classification
        config: default
        split: test
        revision: None
      metrics:
      - type: accuracy
        value: 79.5684803001876
        verified: false
      - type: ap
        value: 42.671935929201524
        verified: false
      - type: f1
        value: 73.31912729103752
        verified: false
    - task:
        type: STS
      dataset:
        name: MTEB LCQMC
        type: C-MTEB/LCQMC
        config: default
        split: test
        revision: None
      metrics:
      - type: cos_sim_pearson
        value: 68.62670112113864
        verified: false
      - type: cos_sim_spearman
        value: 75.74009123170768
        verified: false
      - type: euclidean_pearson
        value: 73.93002595958237
        verified: false
      - type: euclidean_spearman
        value: 75.35222935003587
        verified: false
      - type: manhattan_pearson
        value: 73.89870445158144
        verified: false
      - type: manhattan_spearman
        value: 75.31714936339398
        verified: false
    - task:
        type: Reranking
      dataset:
        name: MTEB MMarcoReranking
        type: C-MTEB/Mmarco-reranking
        config: default
        split: dev
        revision: None
      metrics:
      - type: map
        value: 31.5372713650176
        verified: false
      - type: mrr
        value: 30.163095238095238
        verified: false
    - task:
        type: Retrieval
      dataset:
        name: MTEB MMarcoRetrieval
        type: C-MTEB/MMarcoRetrieval
        config: default
        split: dev
        revision: None
      metrics:
      - type: map_at_1
        value: 65.054
        verified: false
      - type: map_at_10
        value: 74.156
        verified: false
      - type: map_at_100
        value: 74.523
        verified: false
      - type: map_at_1000
        value: 74.535
        verified: false
      - type: map_at_3
        value: 72.269
        verified: false
      - type: map_at_5
        value: 73.41
        verified: false
      - type: mrr_at_1
        value: 67.24900000000001
        verified: false
      - type: mrr_at_10
        value: 74.78399999999999
        verified: false
      - type: mrr_at_100
        value: 75.107
        verified: false
      - type: mrr_at_1000
        value: 75.117
        verified: false
      - type: mrr_at_3
        value: 73.13499999999999
        verified: false
      - type: mrr_at_5
        value: 74.13499999999999
        verified: false
      - type: ndcg_at_1
        value: 67.24900000000001
        verified: false
      - type: ndcg_at_10
        value: 77.96300000000001
        verified: false
      - type: ndcg_at_100
        value: 79.584
        verified: false
      - type: ndcg_at_1000
        value: 79.884
        verified: false
      - type: ndcg_at_3
        value: 74.342
        verified: false
      - type: ndcg_at_5
        value: 76.278
        verified: false
      - type: precision_at_1
        value: 67.24900000000001
        verified: false
      - type: precision_at_10
        value: 9.466
        verified: false
      - type: precision_at_100
        value: 1.027
        verified: false
      - type: precision_at_1000
        value: 0.105
        verified: false
      - type: precision_at_3
        value: 27.955999999999996
        verified: false
      - type: precision_at_5
        value: 17.817
        verified: false
      - type: recall_at_1
        value: 65.054
        verified: false
      - type: recall_at_10
        value: 89.113
        verified: false
      - type: recall_at_100
        value: 96.369
        verified: false
      - type: recall_at_1000
        value: 98.714
        verified: false
      - type: recall_at_3
        value: 79.45400000000001
        verified: false
      - type: recall_at_5
        value: 84.06
        verified: false
    - task:
        type: Classification
      dataset:
        name: MTEB MassiveIntentClassification (zh-CN)
        type: mteb/amazon_massive_intent
        config: zh-CN
        split: test
        revision: 31efe3c427b0bae9c22cbb560b8f15491cc6bed7
      metrics:
      - type: accuracy
        value: 68.1977135171486
        verified: false
      - type: f1
        value: 67.23114308718404
        verified: false
    - task:
        type: Classification
      dataset:
        name: MTEB MassiveScenarioClassification (zh-CN)
        type: mteb/amazon_massive_scenario
        config: zh-CN
        split: test
        revision: 7d571f92784cd94a019292a1f45445077d0ef634
      metrics:
      - type: accuracy
        value: 71.92669804976462
        verified: false
      - type: f1
        value: 72.90628475628779
        verified: false
    - task:
        type: Retrieval
      dataset:
        name: MTEB MedicalRetrieval
        type: C-MTEB/MedicalRetrieval
        config: default
        split: dev
        revision: None
      metrics:
      - type: map_at_1
        value: 49.2
        verified: false
      - type: map_at_10
        value: 54.539
        verified: false
      - type: map_at_100
        value: 55.135
        verified: false
      - type: map_at_1000
        value: 55.19199999999999
        verified: false
      - type: map_at_3
        value: 53.383
        verified: false
      - type: map_at_5
        value: 54.142999999999994
        verified: false
      - type: mrr_at_1
        value: 49.2
        verified: false
      - type: mrr_at_10
        value: 54.539
        verified: false
      - type: mrr_at_100
        value: 55.135999999999996
        verified: false
      - type: mrr_at_1000
        value: 55.19199999999999
        verified: false
      - type: mrr_at_3
        value: 53.383
        verified: false
      - type: mrr_at_5
        value: 54.142999999999994
        verified: false
      - type: ndcg_at_1
        value: 49.2
        verified: false
      - type: ndcg_at_10
        value: 57.123000000000005
        verified: false
      - type: ndcg_at_100
        value: 60.21300000000001
        verified: false
      - type: ndcg_at_1000
        value: 61.915
        verified: false
      - type: ndcg_at_3
        value: 54.772
        verified: false
      - type: ndcg_at_5
        value: 56.157999999999994
        verified: false
      - type: precision_at_1
        value: 49.2
        verified: false
      - type: precision_at_10
        value: 6.52
        verified: false
      - type: precision_at_100
        value: 0.8009999999999999
        verified: false
      - type: precision_at_1000
        value: 0.094
        verified: false
      - type: precision_at_3
        value: 19.6
        verified: false
      - type: precision_at_5
        value: 12.44
        verified: false
      - type: recall_at_1
        value: 49.2
        verified: false
      - type: recall_at_10
        value: 65.2
        verified: false
      - type: recall_at_100
        value: 80.10000000000001
        verified: false
      - type: recall_at_1000
        value: 93.89999999999999
        verified: false
      - type: recall_at_3
        value: 58.8
        verified: false
      - type: recall_at_5
        value: 62.2
        verified: false
    - task:
        type: Classification
      dataset:
        name: MTEB MultilingualSentiment
        type: C-MTEB/MultilingualSentiment-classification
        config: default
        split: validation
        revision: None
      metrics:
      - type: accuracy
        value: 63.29333333333334
        verified: false
      - type: f1
        value: 63.03293854259612
        verified: false
    - task:
        type: PairClassification
      dataset:
        name: MTEB Ocnli
        type: C-MTEB/OCNLI
        config: default
        split: validation
        revision: None
      metrics:
      - type: cos_sim_accuracy
        value: 75.69030860855442
        verified: false
      - type: cos_sim_ap
        value: 80.6157833772759
        verified: false
      - type: cos_sim_f1
        value: 77.87524366471735
        verified: false
      - type: cos_sim_precision
        value: 72.3076923076923
        verified: false
      - type: cos_sim_recall
        value: 84.37170010559663
        verified: false
      - type: dot_accuracy
        value: 67.78559826746074
        verified: false
      - type: dot_ap
        value: 72.00871467527499
        verified: false
      - type: dot_f1
        value: 72.58722247394654
        verified: false
      - type: dot_precision
        value: 63.57142857142857
        verified: false
      - type: dot_recall
        value: 84.58289334741288
        verified: false
      - type: euclidean_accuracy
        value: 75.20303194369248
        verified: false
      - type: euclidean_ap
        value: 80.98587256415605
        verified: false
      - type: euclidean_f1
        value: 77.26396917148362
        verified: false
      - type: euclidean_precision
        value: 71.03631532329496
        verified: false
      - type: euclidean_recall
        value: 84.68848996832101
        verified: false
      - type: manhattan_accuracy
        value: 75.20303194369248
        verified: false
      - type: manhattan_ap
        value: 80.93460699513219
        verified: false
      - type: manhattan_f1
        value: 77.124773960217
        verified: false
      - type: manhattan_precision
        value: 67.43083003952569
        verified: false
      - type: manhattan_recall
        value: 90.07391763463569
        verified: false
      - type: max_accuracy
        value: 75.69030860855442
        verified: false
      - type: max_ap
        value: 80.98587256415605
        verified: false
      - type: max_f1
        value: 77.87524366471735
        verified: false
    - task:
        type: Classification
      dataset:
        name: MTEB OnlineShopping
        type: C-MTEB/OnlineShopping-classification
        config: default
        split: test
        revision: None
      metrics:
      - type: accuracy
        value: 87.00000000000001
        verified: false
      - type: ap
        value: 83.24372135949511
        verified: false
      - type: f1
        value: 86.95554191530607
        verified: false
    - task:
        type: STS
      dataset:
        name: MTEB PAWSX
        type: C-MTEB/PAWSX
        config: default
        split: test
        revision: None
      metrics:
      - type: cos_sim_pearson
        value: 37.57616811591219
        verified: false
      - type: cos_sim_spearman
        value: 41.490259084930045
        verified: false
      - type: euclidean_pearson
        value: 38.9155043692188
        verified: false
      - type: euclidean_spearman
        value: 39.16056534305623
        verified: false
      - type: manhattan_pearson
        value: 38.76569892264335
        verified: false
      - type: manhattan_spearman
        value: 38.99891685590743
        verified: false
    - task:
        type: STS
      dataset:
        name: MTEB QBQTC
        type: C-MTEB/QBQTC
        config: default
        split: test
        revision: None
      metrics:
      - type: cos_sim_pearson
        value: 35.44858610359665
        verified: false
      - type: cos_sim_spearman
        value: 38.11128146262466
        verified: false
      - type: euclidean_pearson
        value: 31.928644189822457
        verified: false
      - type: euclidean_spearman
        value: 34.384936631696554
        verified: false
      - type: manhattan_pearson
        value: 31.90586687414376
        verified: false
      - type: manhattan_spearman
        value: 34.35770153777186
        verified: false
    - task:
        type: STS
      dataset:
        name: MTEB STS22 (zh)
        type: mteb/sts22-crosslingual-sts
        config: zh
        split: test
        revision: 6d1ba47164174a496b7fa5d3569dae26a6813b80
      metrics:
      - type: cos_sim_pearson
        value: 66.54931957553592
        verified: false
      - type: cos_sim_spearman
        value: 69.25068863016632
        verified: false
      - type: euclidean_pearson
        value: 50.26525596106869
        verified: false
      - type: euclidean_spearman
        value: 63.83352741910006
        verified: false
      - type: manhattan_pearson
        value: 49.98798282198196
        verified: false
      - type: manhattan_spearman
        value: 63.87649521907841
        verified: false
    - task:
        type: STS
      dataset:
        name: MTEB STSB
        type: C-MTEB/STSB
        config: default
        split: test
        revision: None
      metrics:
      - type: cos_sim_pearson
        value: 82.52782476625825
        verified: false
      - type: cos_sim_spearman
        value: 82.55618986168398
        verified: false
      - type: euclidean_pearson
        value: 78.48190631687673
        verified: false
      - type: euclidean_spearman
        value: 78.39479731354655
        verified: false
      - type: manhattan_pearson
        value: 78.51176592165885
        verified: false
      - type: manhattan_spearman
        value: 78.42363787303265
        verified: false
    - task:
        type: Reranking
      dataset:
        name: MTEB T2Reranking
        type: C-MTEB/T2Reranking
        config: default
        split: dev
        revision: None
      metrics:
      - type: map
        value: 67.36693873615643
        verified: false
      - type: mrr
        value: 77.83847701797939
        verified: false
    - task:
        type: Retrieval
      dataset:
        name: MTEB T2Retrieval
        type: C-MTEB/T2Retrieval
        config: default
        split: dev
        revision: None
      metrics:
      - type: map_at_1
        value: 25.795
        verified: false
      - type: map_at_10
        value: 72.258
        verified: false
      - type: map_at_100
        value: 76.049
        verified: false
      - type: map_at_1000
        value: 76.134
        verified: false
      - type: map_at_3
        value: 50.697
        verified: false
      - type: map_at_5
        value: 62.324999999999996
        verified: false
      - type: mrr_at_1
        value: 86.634
        verified: false
      - type: mrr_at_10
        value: 89.792
        verified: false
      - type: mrr_at_100
        value: 89.91900000000001
        verified: false
      - type: mrr_at_1000
        value: 89.923
        verified: false
      - type: mrr_at_3
        value: 89.224
        verified: false
      - type: mrr_at_5
        value: 89.608
        verified: false
      - type: ndcg_at_1
        value: 86.634
        verified: false
      - type: ndcg_at_10
        value: 80.589
        verified: false
      - type: ndcg_at_100
        value: 84.812
        verified: false
      - type: ndcg_at_1000
        value: 85.662
        verified: false
      - type: ndcg_at_3
        value: 82.169
        verified: false
      - type: ndcg_at_5
        value: 80.619
        verified: false
      - type: precision_at_1
        value: 86.634
        verified: false
      - type: precision_at_10
        value: 40.389
        verified: false
      - type: precision_at_100
        value: 4.93
        verified: false
      - type: precision_at_1000
        value: 0.513
        verified: false
      - type: precision_at_3
        value: 72.104
        verified: false
      - type: precision_at_5
        value: 60.425
        verified: false
      - type: recall_at_1
        value: 25.795
        verified: false
      - type: recall_at_10
        value: 79.565
        verified: false
      - type: recall_at_100
        value: 93.24799999999999
        verified: false
      - type: recall_at_1000
        value: 97.595
        verified: false
      - type: recall_at_3
        value: 52.583999999999996
        verified: false
      - type: recall_at_5
        value: 66.175
        verified: false
    - task:
        type: Classification
      dataset:
        name: MTEB TNews
        type: C-MTEB/TNews-classification
        config: default
        split: validation
        revision: None
      metrics:
      - type: accuracy
        value: 47.648999999999994
        verified: false
      - type: f1
        value: 46.28925837008413
        verified: false
    - task:
        type: Clustering
      dataset:
        name: MTEB ThuNewsClusteringP2P
        type: C-MTEB/ThuNewsClusteringP2P
        config: default
        split: test
        revision: None
      metrics:
      - type: v_measure
        value: 54.07641891287953
        verified: false
    - task:
        type: Clustering
      dataset:
        name: MTEB ThuNewsClusteringS2S
        type: C-MTEB/ThuNewsClusteringS2S
        config: default
        split: test
        revision: None
      metrics:
      - type: v_measure
        value: 53.423702062353954
        verified: false
    - task:
        type: Retrieval
      dataset:
        name: MTEB VideoRetrieval
        type: C-MTEB/VideoRetrieval
        config: default
        split: dev
        revision: None
      metrics:
      - type: map_at_1
        value: 55.7
        verified: false
      - type: map_at_10
        value: 65.923
        verified: false
      - type: map_at_100
        value: 66.42
        verified: false
      - type: map_at_1000
        value: 66.431
        verified: false
      - type: map_at_3
        value: 63.9
        verified: false
      - type: map_at_5
        value: 65.225
        verified: false
      - type: mrr_at_1
        value: 55.60000000000001
        verified: false
      - type: mrr_at_10
        value: 65.873
        verified: false
      - type: mrr_at_100
        value: 66.36999999999999
        verified: false
      - type: mrr_at_1000
        value: 66.381
        verified: false
      - type: mrr_at_3
        value: 63.849999999999994
        verified: false
      - type: mrr_at_5
        value: 65.17500000000001
        verified: false
      - type: ndcg_at_1
        value: 55.7
        verified: false
      - type: ndcg_at_10
        value: 70.621
        verified: false
      - type: ndcg_at_100
        value: 72.944
        verified: false
      - type: ndcg_at_1000
        value: 73.25399999999999
        verified: false
      - type: ndcg_at_3
        value: 66.547
        verified: false
      - type: ndcg_at_5
        value: 68.93599999999999
        verified: false
      - type: precision_at_1
        value: 55.7
        verified: false
      - type: precision_at_10
        value: 8.52
        verified: false
      - type: precision_at_100
        value: 0.958
        verified: false
      - type: precision_at_1000
        value: 0.098
        verified: false
      - type: precision_at_3
        value: 24.733
        verified: false
      - type: precision_at_5
        value: 16
        verified: false
      - type: recall_at_1
        value: 55.7
        verified: false
      - type: recall_at_10
        value: 85.2
        verified: false
      - type: recall_at_100
        value: 95.8
        verified: false
      - type: recall_at_1000
        value: 98.3
        verified: false
      - type: recall_at_3
        value: 74.2
        verified: false
      - type: recall_at_5
        value: 80
        verified: false
    - task:
        type: Classification
      dataset:
        name: MTEB Waimai
        type: C-MTEB/waimai-classification
        config: default
        split: test
        revision: None
      metrics:
      - type: accuracy
        value: 84.54
        verified: false
      - type: ap
        value: 66.13603199670062
        verified: false
      - type: f1
        value: 82.61420654584116
        verified: false
transformersInfo:
  auto_model: AutoModel
gguf:
  total: 160223232
  architecture: jina-bert-v2
  context_length: 8192
  causal: false
  bos_token: <s>
  eos_token: </s>
  totalFileSize: 172173312
siblings:
- rfilename: .gitattributes
- rfilename: README.md
- rfilename: jina-embeddings-v2-base-zh-q8_0.gguf
spaces: []
createdAt: '2025-01-24T10:45:10.000Z'
usedStorage: 172173312
downloadsAllTime: 312
inferenceProviderMapping: {}
configJson: null
onnxFiles: {}
safetensorsSizeMb: 0.0
approxSizeMb: 0.0
fetchedAt: '2026-06-10T07:15:01.000Z'
